### PR TITLE
feat: Add ignore flag to emptyInterface analyzer

### PR DESCRIPTION
**Pull request by jespino**

### CODE REVIEW

**Review by agnivade — COMMENTED** [review]
This looks like the exact same code in https://github.com/mattermost/mattermost-govet/blob/72e7752bcf59b57688fcb41173a6a1583c405adf/inconsistentReceiverName/inconsistentReceiverName.go#L92-L99. Can we refactor this to a common function?

**Comment by jespino** [comment]
@agnivade done

**Review by agnivade — APPROVED** [review]
Thanks

**Review by agarciamontoro — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
