### PR TITLE
Bump to use v6 paths

### PR DESCRIPTION
**Pull request by agnivade**

### CODE REVIEW

**Comment by agnivade** [comment]
Soliciting for input here. We need to do something to avoid breaking mattermost-govet in all other release branches. That's because we are doing a fetch off master via - `GO111MODULE=off go get -u github.com/mattermost/mattermost-govet`. I chose to bump the major version of the tool to v2.

Open to any other ideas here.

**Review by streamer45 — APPROVED** [review]
Sounds good to me :+1:

**Review by isacikgoz — APPROVED** [review]
Sounds good indeed. Just a question; would it make sense to align version of the tool with the server version?

**Comment by agnivade** [comment]
> Just a question; would it make sense to align version of the tool with the server version?

I would prefer not to. This would mean every time we bump server major version, we need to bump the tool's version unecessarily. It's okay to have separate versions for separate tools.

**Comment by agnivade** [comment]
Ah wait, no this won't work :( Since `GO111MODULE` is `off`, the tool will _always_ take the latest HEAD and still break for old release branches.

The `v2` suffix only works for module mode.

Any other ideas?

@streamer45 @isacikgoz

**Comment by streamer45** [comment]
> Any other ideas?
> 
> @streamer45 @isacikgoz

Can we update non v6 branches (only the live ones of course) to fetch the tool from a specific commit? Otherwise let's just build a release of this and do what we already to with `mmctl`, downloading the binary if missing.

**Comment by agnivade** [comment]
> Can we update non v6 branches (only the live ones of course) to fetch the tool from a specific commit? 

I think that's the only way right? Anything else will break the old branches.

I was trying to avoid updating all the way back to ESR, but it looks like there is no alternative.

Can you clarify what is the mmctl solution? Even if we build a binary, the old branches will still fetch the latest code and break right?

**Comment by isacikgoz** [comment]
It seems like the best option to update old branches. Also the specific version of govet should be downloaded if the tool already exists but has different version then expected.

**Comment by streamer45** [comment]
> Can you clarify what is the mmctl solution? Even if we build a binary, the old branches will still fetch the latest code and break right?

Yeah, both my proposed options would require updates to older branches. If you absolutely wanted to avoid that then we'd have to wait until old versions phase out and in the meantime point v6+ to some other branch, later to be merged into master.

**Comment by agnivade** [comment]
> If you absolutely wanted to avoid that then we'd have to wait until old versions phase out and in the meantime point v6+ to some other branch, later to be merged into master.

Ah I think I like that. We can change the default branch in GitHub so that all PRs by default are created against that. Apart from announcing this broadly of course.

Any picks for the branch name? I am thinking `new`/`dev`.

**Comment by streamer45** [comment]
> Any picks for the branch name? I am thinking `new`/`dev`.

`new` or `next` sound good to me.

**Comment by agnivade** [comment]
Going with `new`.

**Comment by agnivade** [comment]
All done. Merging to `new`.

**Pull request merged**
